name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AKIA4MSJDMVWDZSTJJGV }}
          aws-secret-access-key: ${{ secrets.bj4ZGW+9q+12j2jWVqWgfYs0mIANllA3/isyb8rM }}
          aws-region: ${{ secrets.us-east-1 }}

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - run: python lambda_function.py

      - name: Lambda Build & Update
        run: |
          pip3 install awscli
          cd lambda && zip -r package.zip ./*
          aws lambda update-function-code --function-name github-actions --zip-file fileb://package.zip --publish